sonar.organization=headlesstarry
sonar.projectKey=HeadlessTarry_HomeAssistant-Test-Harness

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.exclusions=**/tests/**,**/*.md
sonar.test.exclusions=**/*.md
sonar.coverage.exclusions=**/*.md
